### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by inpharmaticist** [billygarrison/bitcoin-scripts#1]
This is sick. I didn't know you could pass in variables this way.  For this line:

> From the command line, run the script passing in the number of blocks you'd like to check for Taproot readiness. To check the last 144 blocks, do `./taproot-signalling.sh 144`

The command should start with `bash` no?

**Comment by billygarrison** [comment]
I'm no Linux pro, but I never use the `bash` command. I just make the file executable (`chmod +x ./taproot-signalling.sh`) and then run it as an executable `./taproot-signalling.sh 144`.

For the variables, you can access the first command line argument using `$1`, the second with `$2`, etc.
